repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-json
      - id: check-toml
  - repo: https://github.com/johnnymorganz/stylua
    rev: 28e1d7b5db3f2c6c53580963c79c5e6a5b374ca0 # frozen: v2.4.0
    hooks:
      - id: stylua-github
  - repo: https://github.com/hoxbro/prettier-pre-commit
    rev: 86ff8f664c20f581d71c90a6ea0073c1bcafe1e5 # frozen: v3.8.1
    hooks:
      - id: prettier
        types_or:
          - markdown
          - yaml
          - css
  - repo: https://github.com/hoxbro/taplo-pre-commit
    rev: 605f960c3c571f814f535622a688bcde63ee87f6 # frozen: v0.9.3
    hooks:
      - id: taplo
        args:
          [
            --option,
            align_comments=false,
            --option,
            column_width=100,
            --option,
            "indent_string=    ",
          ]
